<?php return array(
    'root' => array(
        'name' => 'laravel/laravel',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '8ed1a795c8fc60c23652c0b9165488b793d9f4de',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'alexpechkarev/geometry-library' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'ebbf02c3e907e0bd19c9474fd5eb77b9ca1ce414',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alexpechkarev/geometry-library',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alexpechkarev/google-maps' => array(
            'pretty_version' => '1.0.7',
            'version' => '1.0.7.0',
            'reference' => '467a9360fa9764e4e3a57a51305fcb1e2f11ffbc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alexpechkarev/google-maps',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'banago/bridge' => array(
            'pretty_version' => 'v1.0.10',
            'version' => '1.0.10.0',
            'reference' => '81077125ddb426bfeb77ece29215bec0085df3f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../banago/bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-dompdf' => array(
            'pretty_version' => 'v0.8.2',
            'version' => '0.8.2.0',
            'reference' => '7dcdecfa125c174d0abe723603633dc2756ea3af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'classpreloader/classpreloader' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '4729e438e0ada350f91148e7d4bb9809342575ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../classpreloader/classpreloader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'dingo/api' => array(
            'pretty_version' => 'v1.0.0-beta8',
            'version' => '1.0.0.0-beta8',
            'reference' => '46cffad61942caa094dd876155e503b6819c5095',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dingo/api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dingo/blueprint' => array(
            'pretty_version' => 'v0.2.4',
            'version' => '0.2.4.0',
            'reference' => '1dc93b8ea443fbbdaaca0582572ee6ca53afccfd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dingo/blueprint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dnoegel/php-xdg-base-dir' => array(
            'pretty_version' => '0.1',
            'version' => '0.1.0.0',
            'reference' => '265b8593498b997dc2d31e75b89f053b5cc9621a',
            'type' => 'project',
            'install_path' => __DIR__ . '/../dnoegel/php-xdg-base-dir',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => 'v1.8.0',
            'version' => '1.8.0.0',
            'reference' => '904dca4eb10715b92569fbcd79e201d5c349b6bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'reference' => '5527a48b7313d15261292c149e55e26eae771b0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'a2c590166b2133a4633738648b6b064edae0814a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'e17f069ede36f7534b95adec71910ed1b49c74ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v0.8.3',
            'version' => '0.8.3.0',
            'reference' => '75f13c700009be21a1965dc2c5b68a8708c22ba2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.7.0',
            'version' => '5.7.0.0',
            'reference' => '2d8250638b33d73e7a87add65f47fabf91f8ad9b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fadion/maneuver' => array(
            'pretty_version' => 'dev-l5',
            'version' => 'dev-l5',
            'reference' => '1c34fdfd3496acaf0a19efdac350c359e57d1b69',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fadion/maneuver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fzaninotto/faker' => array(
            'pretty_version' => 'v1.8.0',
            'version' => '1.8.0.0',
            'reference' => 'f72816b43e74063c8b10357394b6bba8cb1c10de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fzaninotto/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.4.1',
            'version' => '6.4.1.0',
            'reference' => '0895c932405407fd3a7368b6910c09a24d26db11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'a59da6cf61d80060647ff4d3eb2c03a2bc694646',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '239400de7a173fe9901b9ac7c06497751f00727a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'b37020aa976fa52d3de9aa904aa2522dc518f79c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/exception' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'jakeasmith/http_build_url' => array(
            'pretty_version' => '0.1.5',
            'version' => '0.1.5.0',
            'reference' => '9d84710feab0f3d7c04c1e11dccef30ee350aad6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakeasmith/http_build_url',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-color' => array(
            'pretty_version' => 'v0.2',
            'version' => '0.2.0.0',
            'reference' => 'd5deaecff52a0d61ccb613bb3804088da0307191',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-color',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-highlighter' => array(
            'pretty_version' => 'v0.3.2',
            'version' => '0.3.2.0',
            'reference' => '7daa75df45242c8d5b75a22c00a201e7954e4fb5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-highlighter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeremeamia/superclosure' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => '5707d5821b30b9a07acfb4d76949784aaa0e9ce9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeremeamia/SuperClosure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'kylekatarnls/update-helper' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '5786fa188e0361b9adf9e8199d7280d1b2db165e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../kylekatarnls/update-helper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/framework' => array(
            'pretty_version' => 'v5.2.45',
            'version' => '5.2.45.0',
            'reference' => '2a79f920d5584ec6df7cf996d922a742d11095d1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/laravel' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '8ed1a795c8fc60c23652c0b9165488b793d9f4de',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravelcollective/html' => array(
            'pretty_version' => 'v5.2.6',
            'version' => '5.2.6.0',
            'reference' => '4f6701c7c3f6ff2aee1f4ed205ed6820e1e3048e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravelcollective/html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '1.0.57',
            'version' => '1.0.57.0',
            'reference' => '0e9db7f0b96b9f12dcf6f65bc34b72b1a30ea55a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/fractal' => array(
            'pretty_version' => '0.18.0',
            'version' => '0.18.0.0',
            'reference' => '4e553dae1a9402adbe11c81430a64675dc97b4fc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/fractal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maatwebsite/excel' => array(
            'pretty_version' => '2.1.30',
            'version' => '2.1.30.0',
            'reference' => 'f5540c4ba3ac50cebd98b09ca42e61f926ef299f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maatwebsite/excel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mockery/mockery' => array(
            'pretty_version' => '0.9.11',
            'version' => '0.9.11.0',
            'reference' => 'be9bf28d8e57d67883cba9fcadfcff8caab667f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mockery/mockery',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.25.1',
            'version' => '1.25.1.0',
            'reference' => '70e65a5470a42cfec1a7da00d30edb6e617e8dcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'reference' => '9504fa9ea681b586028adaaa0877db4aecf32bad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/cron-expression',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '1.39.1',
            'version' => '1.39.1.0',
            'reference' => '4be0c005164249208ce1b5ca633cd57bdd42ff33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => '4dd659edadffdc2143e4753df655d866dbfeedf0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => '9b3899e3c3ddde89016f576edb8c489708ad64cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.1',
            'version' => '0.5.1.0',
            'reference' => '760148820110a1ae0936e5cc35851e25a938bc97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => 'v0.3.3',
            'version' => '0.3.3.0',
            'reference' => '5fa61b65e612ce1ae15f69b3d223cb14ecc60e32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'bf329f6c1aadea3299f08ee804682b7c45b326a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'reference' => '9c977708995954784726e25d0cd1dddf4e65b0f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpexcel' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'reference' => '1441011fb7ecdd8cc689878f54f8b58a6805f870',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpexcel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => 'f6811d96d97bdf400077a0cc100ae56aa32b9203',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '2.2.4',
            'version' => '2.2.4.0',
            'reference' => 'eabf68b476ac7d0f73793aada060f1c1a9bf8979',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'reference' => '3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.4.12',
            'version' => '1.4.12.0',
            'reference' => '1ce90ba27c42e4e44e6d8458241466380b51fa16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '4.8.36',
            'version' => '4.8.36.0',
            'reference' => '46023de9a91eec7dfb06cc56cb4e260017298517',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '2.3.8',
            'version' => '2.3.8.0',
            'reference' => 'ac8e7a3db35738d56ee9a76e78a4e03d97628983',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '446d54b4cb6bf489fc9d75f55843658e6f25d801',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.7.2',
            'version' => '0.7.2.0',
            'reference' => 'e64e10b20f8d229cac76399e1f3edddb57a0f280',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.3.0',
            'version' => '8.3.0.0',
            'reference' => '91bcc3e3fdb7386c9a2e0e0aa09ca75cc43f121f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sammyk/laravel-facebook-sdk' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'reference' => '2213691019e87e589f2fcc4d0a494deade63973f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sammyk/laravel-facebook-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => '7f066a26a962dbe58ddea9f72a4e82874a3975a4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '1.3.8',
            'version' => '1.3.8.0',
            'reference' => 'be2c607e43ce4c89ecd60e75c6a85c126e754aea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '42c4c2eec485ee3e159ec9884f95b431287edde4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'bc37d50fea7d017d3d340f230811c9f1d7280af4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => '181b89f18a90f8925ef805f950d47a7190e9b950',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '926061e74229e935d3c5b4e9ba87237316c6693f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.33',
            'version' => '3.4.33.0',
            'reference' => 'f819f71ae3ba6f396b4c015bd5895de7d2f1f85f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '697c527acd9ea1b2d3efac34d9806bf255278b0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v3.4.33',
            'version' => '3.4.33.0',
            'reference' => '6bcffd2eabc4ca087faaaf54e26c8ff3a40284f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v3.4.33',
            'version' => '3.4.33.0',
            'reference' => 'f9031c22ec127d4a2450760f81a8677fe8a10177',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '3eb4e64c6145ef8b92adefb618a74ebdde9e3fe9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '49ba00f8ede742169cb6b70abe33243f4d673f82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => 'd97ba4425e36e79c794e7d14ff36f00f081b37b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => '550ebaac289296ce228a706d0867afc34687e3f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'b42a2f66e8f1b15ccf25652c3424265923eb4f17',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => '0e3b212e96a51338639d8ce175c046d7729c3403',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php56',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-util' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => '4317de1386717b4c22caed7725350a8887ab205c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-util',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '768debc5996f599c4372b322d9061dba2a4bf505',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '9038984bd9c05ab07280121e9e10f61a7231457b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => 'eee6c664853fd0576f21ae25725cfffeafe83f26',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'reference' => '1f7e071aafc6676fcb6e3f0497f87c2397247377',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.3.18',
            'version' => '3.3.18.0',
            'reference' => 'af615970e265543a26ee712c958404eb9b7ac93d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'themattharris/tmhoauth' => array(
            'pretty_version' => '0.8.4',
            'version' => '0.8.4.0',
            'reference' => '455552d6c57549632644b6c9ac9204766be2b5ee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../themattharris/tmhoauth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'thujohn/twitter' => array(
            'pretty_version' => '2.2.5',
            'version' => '2.2.5.0',
            'reference' => 'ff414bdadba3f1570ca211355e5359ec266552d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../thujohn/twitter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tightenco/collect' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.2.45',
            ),
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'reference' => 'b43b05cf43c1b6d849478965062b6ef73e223bb5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v2.6.1',
            'version' => '2.6.1.0',
            'reference' => '2a7dcf7e3e02dc5e701004e51a6f304b713107d5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '88e6d84706d09a236046d686bbea96f07b3a34f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-oracle' => array(
            'pretty_version' => 'v6.29.3',
            'version' => '6.29.3.0',
            'reference' => '5ccbe38affa0a9930a2add19684e012bed09f62d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-oracle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
